config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  match '/sign_up' => 'pages#sign_up', as: :sign_up, via: [:get, :post]
  match '/sign_in' => 'pages#sign_in', as: :sign_in, via: [:get, :post]
  get '/sign_out' => 'pages#sign_out', as: :sign_out
  get '/dashboard' => 'pages#dashboard'
  post '/submit_patient', to: 'pages#submit_patient', as: :submit_patient
  post '/submit_doctor', to: 'pages#submit_doctor', as: :submit_doctor
  post '/submit_appointment', to: 'pages#submit_appointment', as: :submit_appointment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    return redirect_to dashboard_path if session['token'].present?
  end

  def sign_up
    return redirect_to dashboard_path if session['token'].present?

    url = ENV['REMOTE_HOST']+'/sign-up'
    body = {
      email: params[:sign_up_email],
      password: params[:sign_up_password],
      confirm_password: params[:sign_up_confirm_password]
    }

    @response = HTTParty.post( url, :body => body )

    if @response['status'] == STATUS_SUCCESS
      session['token'] = @response['token']
      session['user'] = @response['user']
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def sign_in
    return redirect_to dashboard_path if session['token'].present?

    url = ENV['REMOTE_HOST']+'/sign-in'
    body = {
      email: params[:email],
      password: params[:password]
    }

    @response = HTTParty.post( url, :body => body )

    if @response['status'] == STATUS_SUCCESS
      session['token'] = @response['token']
      session['user'] = @response['user']
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def sign_out
    url = ENV['REMOTE_HOST']+'/sign-out'
    @response = HTTParty.get( url, :headers => { 'Content-Type' => 'application/json', 'Authorization' => "Token token=#{session[:token]}" } )

    if @response['status'] == STATUS_SUCCESS
      session['token'] = nil
      session['user'] = nil
      redirect_to root_path
    else
      redirect_to dashboard_path
    end
  end

  def dashboard
    get_update_list
  end

  def submit_patient
    url = ENV['REMOTE_HOST']+'/create-patient'
    body = {
      name: params[:name],
      phone_number: params[:phone_number]
    }.to_json

    @response = HTTParty.post( url, body: body, headers: { 'Content-Type' => 'application/json', 'Authorization' => "Token token=#{session[:token]}" } )
  end

  def submit_doctor
    url = ENV['REMOTE_HOST']+'/create-doctor'
    body = {
      name: params[:name],
      phone_number: params[:phone_number],
      specialization: params[:specialization]
    }.to_json

    @response = HTTParty.post( url, body: body, headers: { 'Content-Type' => 'application/json', 'Authorization' => "Token token=#{session[:token]}" } )
  end

  def submit_appointment
    url = ENV['REMOTE_HOST']+'/create-appointment'
    body = {
      doctor_id: params[:doctor_id],
      patient_id: params[:patient_id],
      disease: params[:disease]
    }.to_json

    @response = HTTParty.post( url, body: body, headers: { 'Content-Type' => 'application/json', 'Authorization' => "Token token=#{session[:token]}" } )
  end

  private

  def get_update_list
    url = ENV['REMOTE_HOST']+'/get-dashboards'
    @response = HTTParty.get( url, :headers => { 'Content-Type' => 'application/json', 'Authorization' => "Token token=#{session[:token]}" } )

    begin
      if @response['status'] == STATUS_SUCCESS
        @doctors = @response['doctor_lists']
        @patients = @response['patient_lists']
        @appointments = @response['appointments']
      else
        redirect_to root_path
      end
    rescue Exception => e
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.slim
.header
  a.logo[href="#{root_path}"]
    = session[:user]
  .header-right
    = link_to 'Sign Out', sign_out_path, class: 'active'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Tonguestun
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if session[:token].present?
      = render partial: 'layouts/header'
    #myModal.modal.hide[tabindex="-1" role="dialog" aria-labelledby="myModalLabel"]
      .modal-dialog.modal-sm[role="document"]
        .modal-content
          .modal-header
            button.close[type="button" data-dismiss="modal" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
            h4#myModalLabel.modal-title
              | Thank You !
          .modal-body.text-center
            .img
            p.lead
              | Data Created Successfully!
    = yield

app/views/pages/_appointment_lists.slim
.col-md-6.column[style="background-color:#ccc;"]
  .form-block
    h4.text-center Appointment
    = form_tag submit_appointment_path, remote: true do
      .form-group
        = select_tag :doctor_id, options_for_select(doctors.collect {|p| [ p['doctor_name'], p['doctor_id'] ] }), class: 'form-control', prompt: 'Select Doctor'
      .form-group
        = select_tag :patient_id, options_for_select(patients.collect {|p| [ p['patient_name'], p['patient_id'] ] }), class: 'form-control', prompt: 'Select Patient'
      .form-group
        = text_field_tag :disease, nil, class: 'form-control', placeholder: 'Disease'
      .text-center
        = submit_tag "Submit", class: "btn btn-large btn-primary btn-submit"
.col-md-6.column[style="background-color:#ddd;"]
  h4.text-center View Appointment

  table#example.table.table-striped.table-bordered
    thead
      tr
        th
          | Doctor Name
        th
          | Patient Name
        th
          | Diseases
    tbody
      - appointments.each do |appointment|
        tr
          td = appointment['doctor_name']
          td = appointment['patient_name']
          td = appointment['disease']

app/views/pages/dashboard.slim
.col-md-6.column[style="background-color:#aaa;"]
  .form-block
    h4.text-center Patient
    = form_tag submit_patient_path, remote: true do
      .form-group
        = text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Name'
      .form-group
        = text_field_tag :phone_number, params[:phone_number], class: 'form-control', placeholder: 'Phone Number'
      .text-center
        = submit_tag "Submit", class: "btn btn-large btn-primary btn-submit"
.col-md-6.column[style="background-color:#bbb;"]
  .form-block
    h4.text-center Doctor
    = form_tag submit_doctor_path, remote: true do
      .form-group
        = text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Name'
      .form-group
        = text_field_tag :phone_number, params[:phone_number], class: 'form-control', placeholder: 'Phone Number'
      .form-group
        = text_field_tag :specialization, params[:specialization], class: 'form-control', placeholder: 'Specialization'
      .text-center
        = submit_tag "Submit", class: "btn btn-large btn-primary btn-submit"
#appointement_div
  = include_gon(:init => true)
  = render partial: 'pages/appointment_lists', locals: { doctors: @doctors, patients: @patients, appointments: @appointments }

app/views/pages/index.slim
.container
  .row
    .main
      h3
        | Please
        a.login[href="#"]
          | Log In
        |  , or
        a.sign-up[href="#"]
          |  Sign Up
      .login-or
        hr.hr-or
      #sign-in
        = form_tag sign_in_path do
          .form-group
            = label_tag :email
            = text_field_tag :email, nil, class: 'form-control'
          .form-group
            = label_tag :password
            = text_field_tag :password, nil, class: 'form-control'
          .text-center = submit_tag "Sign in", class: "btn btn-large btn-primary"
      #sign-up.hide
        = form_tag sign_up_path do
          .form-group
            = label_tag :email
            = text_field_tag :sign_up_email, nil, class: 'form-control'
          .form-group
            = label_tag :password
            = text_field_tag :sign_up_password, nil, class: 'form-control'
          .form-group
            = label_tag :confirm_password
            = text_field_tag :sign_up_confirm_password, params[:sign_up_confirm_password], class: 'form-control'
          .text-center = submit_tag "Sign Up", class: "btn btn-large btn-primary"

app/views/pages/submit_appointment.js.erb
if ("<%= @response['status'] %>" == '200'){
  $('.form-control').val('')
  $('.lead').text('Data Added Successfully!')
  $('.modal-body .img').addClass('tick-image')
} else {
  $('.lead').text('Something went wrong. Please try again')
  $('.modal-body .img').addClass('cross-image')
}


$('#appointement_div').html('<%= escape_javascript(raw(render partial: 'pages/appointment_lists', locals: { doctors: @response["doctor_lists"], patients: @response["patient_lists"], appointments: @response["appointments"] })) %>');
$('#myModal').modal('show');
$('#myModal').removeClass('hide');

app/views/pages/submit_doctor.js.erb
if ("<%= @response['status'] %>" == '200'){
  $('.form-control').val('')
  $('.lead').text('Data Added Successfully!')
  $('.modal-body .img').addClass('tick-image')
} else {
  $('.lead').text('Something went wrong. Please try again')
  $('.modal-body .img').addClass('cross-image')
}
$('#appointement_div').html('<%= escape_javascript(raw(render partial: 'pages/appointment_lists', locals: { doctors: @response["doctor_lists"], patients: @response["patient_lists"], appointments: @response["appointments"] })) %>');
$('#myModal').modal('show');
$('#myModal').removeClass('hide');

app/views/pages/submit_patient.js.erb
if ("<%= @response['status'] %>" == '200'){
  $('.form-control').val('')
  $('.lead').text('Data Added Successfully!')
  $('.modal-body .img').addClass('tick-image')
} else {
  $('.lead').text('Something went wrong. Please try again')
  $('.modal-body .img').addClass('cross-image')
}

$('#appointement_div').html('<%= escape_javascript(raw(render partial: 'pages/appointment_lists', locals: { doctors: @response["doctor_lists"], patients: @response["patient_lists"], appointments: @response["appointments"] })) %>');
$('#myModal').modal('show');
$('#myModal').removeClass('hide');